name: water_conditioner
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter

  syncfusion_flutter_gauges: ^33.2.8
  syncfusion_flutter_charts: ^33.2.8

  image_picker: ^1.0.7
  url_launcher: ^6.3.0
  flutter_image_compress: ^2.1.0
  http: ^1.6.0
  shared_preferences: ^2.2.2
  intl: ^0.18.1
  flutter_screenutil: ^5.9.3
  flutter_bloc: ^8.1.6
  bloc: ^8.1.4
  get_it: ^7.6.0

  google_nav_bar: ^5.0.6

  firebase_core: ^4.0.0
  firebase_messaging: ^16.0.0
  flutter_local_notifications: ^19.4.0

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.14.1
  flutter_lints: ^6.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true

  assets:
    - assets/bg.png
    - assets/logo.png