import 'dart:io';

import 'package:open_filex/open_filex.dart';
import 'package:path_provider/path_provider.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;

class PdfService {
  static Future<File> generateDailyReport({
    required Map<String, dynamic> report,
  }) async {
    final pdf = pw.Document();

    pdf.addPage(
      pw.MultiPage(
        pageTheme: pw.PageTheme(
          margin: const pw.EdgeInsets.all(30),
          theme: pw.ThemeData.withFont(
            base: pw.Font.helvetica(),
            bold: pw.Font.helveticaBold(),
          ),
        ),

        build: (context) =>
        [
          _buildHeader(),
          pw.SizedBox(height: 20),

          _buildSectionTitle("Report Information"),

          _buildInfoRow(
            "Report Date",
            _formatDate(report["reportDate"] ?? ""),
          ),

          _buildInfoRow(
            "Device ID",
            report["deviceId"]?.toString() ?? "-",
          ),

          _buildInfoRow(
            "Device ON",
            _formatTime(report["deviceOn"]),
          ),

          pw.SizedBox(height: 20),

          _buildSectionTitle("Electrical Readings"),

          _buildInfoRow(
            "Average Voltage",
            "${report["averageVoltage"] ?? 0} V",
          ),

          _buildInfoRow(
            "Average Current 1",
            "${report["averageCurrent1"] ?? 0} A",
          ),

          _buildInfoRow(
            "Average Current 2",
            "${report["averageCurrent2"] ?? 0} A",
          ),

          _buildInfoRow(
            "Average Flow Rate",
            "${report["averageFlowRate"] ?? 0} Lt/Hr",
          ),

          pw.SizedBox(height: 30),

          _buildFooter(),
        ],
      ),
    );

    final directory = await getApplicationDocumentsDirectory();

    final file = File(
      "${directory.path}/Daily_Report_${report["reportDate"]}.pdf",
    );

    await file.writeAsBytes(await pdf.save());

    return file;
  }

  static Future<void> openPdf(File file) async {
    await OpenFilex.open(file.path);
  }

  //========================================================
  // HEADER
  //========================================================

  static pw.Widget _buildHeader() {
    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.center,
      children: [
        pw.Text(
          "WATER CONDITIONER",
          style: pw.TextStyle(
            fontSize: 24,
            fontWeight: pw.FontWeight.bold,
            color: PdfColors.blue800,
          ),
        ),
        pw.SizedBox(height: 5),
        pw.Text(
          "Daily Device Report",
          style: pw.TextStyle(
            fontSize: 16,
            color: PdfColors.grey700,
          ),
        ),
        pw.Divider(
          thickness: 2,
          color: PdfColors.blue800,
        ),
      ],
    );
  }

  //========================================================
  // SECTION TITLE
  //========================================================

  static pw.Widget _buildSectionTitle(String title) {
    return pw.Container(
      width: double.infinity,
      padding: const pw.EdgeInsets.symmetric(
        horizontal: 10,
        vertical: 8,
      ),
      decoration: pw.BoxDecoration(
        color: PdfColors.blue100,
        borderRadius: pw.BorderRadius.circular(6),
      ),
      child: pw.Text(
        title,
        style: pw.TextStyle(
          fontWeight: pw.FontWeight.bold,
          fontSize: 14,
        ),
      ),
    );
  }

  //========================================================
  // INFO ROW
  //========================================================

  static pw.Widget _buildInfoRow(String title,
      String value,) {
    return pw.Container(
      margin: const pw.EdgeInsets.only(top: 10),
      child: pw.Row(
        children: [
          pw.Expanded(
            flex: 4,
            child: pw.Text(
              title,
              style: const pw.TextStyle(
                fontSize: 12,
              ),
            ),
          ),
          pw.Expanded(
            flex: 5,
            child: pw.Text(
              value,
              style: pw.TextStyle(
                fontSize: 12,
                fontWeight: pw.FontWeight.bold,
              ),
            ),
          ),
        ],
      ),
    );
  } //========================================================
  // FOOTER
  //========================================================

  static pw.Widget _buildFooter() {
    return pw.Column(
      children: [

        pw.Divider(),

        pw.SizedBox(height: 10),

        pw.Text(
          "Generated by",
          style: pw.TextStyle(
            fontSize: 11,
            color: PdfColors.grey700,
          ),
        ),

        pw.SizedBox(height: 3),

        pw.Text(
          "Water Conditioner Monitoring System",
          style: pw.TextStyle(
            fontWeight: pw.FontWeight.bold,
            fontSize: 13,
          ),
        ),

        pw.SizedBox(height: 15),

        pw.Text(
          "© 2026 Water Conditioner",
          style: pw.TextStyle(
            color: PdfColors.grey600,
            fontSize: 10,
          ),
        ),
      ],
    );
  }

  //========================================================
  // FORMAT DATE
  //========================================================

  static String _formatDate(String date) {
    if (date.isEmpty) return "-";

    final d = DateTime.parse(date);

    const months = [
      "Jan",
      "Feb",
      "Mar",
      "Apr",
      "May",
      "Jun",
      "Jul",
      "Aug",
      "Sep",
      "Oct",
      "Nov",
      "Dec",
    ];

    return "${d.day} ${months[d.month - 1]} ${d.year}";
  }

  //========================================================
  // FORMAT TIME
  //========================================================

  static String _formatTime(dynamic value) {
    if (value == null) return "-";

    final d = DateTime.parse(value.toString()).toLocal();

    final hour =
    d.hour > 12
        ? d.hour - 12
        : (d.hour == 0 ? 12 : d.hour);

    final minute =
    d.minute.toString().padLeft(2, "0");

    final amPm =
    d.hour >= 12 ? "PM" : "AM";

    return "$hour:$minute $amPm";
  }
}